// Generated by ReScript, PLEASE EDIT WITH CARE


function make(front, back) {
  return {
          front: front,
          back: back
        };
}

var empty = {
  front: "",
  back: ""
};

export {
  empty ,
  make ,
  
}
/* No side effect */
