// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stack from "./stack.bs.js";
import * as Selected from "./selected.bs.js";

var empty = {
  boxes: Stack.empty,
  view: Selected.empty,
  iteration: 0
};

function addCard(t, card) {
  return {
          boxes: Stack.Update.addCard(t.boxes, card),
          view: t.view,
          iteration: t.iteration
        };
}

function startReview(t) {
  return {
          boxes: t.boxes,
          view: Selected.make(Stack.Selectors.getBoxes(t.boxes, t.iteration)),
          iteration: t.iteration
        };
}

function next(t, known) {
  return {
          boxes: t.boxes,
          view: Selected.Update.next(t.view, known),
          iteration: t.iteration
        };
}

var Update = {
  addCard: addCard,
  startReview: startReview,
  next: next
};

export {
  empty ,
  Update ,
  
}
/* Stack Not a pure module */
