// Generated by ReScript, PLEASE EDIT WITH CARE

import * as View from "./view.bs.js";
import * as Stack from "./stack.bs.js";

var empty = {
  stack: Stack.empty,
  view: View.empty,
  iteration: 0
};

function addCard(t, card) {
  return {
          stack: Stack.addCard(t.stack, card),
          view: t.view,
          iteration: t.iteration
        };
}

function startReview(t) {
  var cards = Stack.getCards(t.stack, t.iteration);
  return {
          stack: t.stack,
          view: cards ? View.make({
                  hd: cards.hd,
                  tl: cards.tl
                }) : View.empty,
          iteration: t.iteration
        };
}

function next(t, familiarity) {
  var stack = View.next(t.view, familiarity);
  if (typeof stack === "number") {
    return {
            stack: t.stack,
            view: /* Overview */0,
            iteration: t.iteration
          };
  } else if (stack.TAG === /* InProgress */0) {
    return {
            stack: t.stack,
            view: {
              TAG: /* InProgress */0,
              _0: stack._0,
              _1: stack._1
            },
            iteration: t.iteration
          };
  } else {
    return {
            stack: Stack.updateCards(t.stack, stack._0),
            view: /* Overview */0,
            iteration: t.iteration + 1 | 0
          };
  }
}

export {
  empty ,
  addCard ,
  startReview ,
  next ,
  
}
/* No side effect */
