// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "./card.bs.js";

var emptyReview = {
  toReview: /* [] */0,
  reviewing: Card.empty,
  remember: /* [] */0,
  forget: /* [] */0
};

function make(param) {
  var cards = param.cards;
  if (cards) {
    return /* Review */{
            _0: {
              toReview: cards.tl,
              reviewing: cards.hd,
              remember: /* [] */0,
              forget: /* [] */0
            }
          };
  } else {
    return /* Overview */0;
  }
}

function next(t, known) {
  if (!t) {
    return /* Overview */0;
  }
  var match = t._0;
  var toReview = match.toReview;
  if (!toReview) {
    return /* Overview */0;
  }
  var forget = match.forget;
  var remember = match.remember;
  var reviewing = match.reviewing;
  return /* Review */{
          _0: {
            toReview: toReview.tl,
            reviewing: toReview.hd,
            remember: known ? ({
                  hd: reviewing,
                  tl: remember
                }) : remember,
            forget: known ? forget : ({
                  hd: reviewing,
                  tl: forget
                })
          }
        };
}

var Update = {
  next: next
};

var empty = /* Overview */0;

export {
  emptyReview ,
  empty ,
  make ,
  Update ,
  
}
/* No side effect */
