// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

function make(cards) {
  return cards;
}

function addCard(t, card) {
  return {
          cards: {
            hd: card,
            tl: t.cards
          }
        };
}

function updateCard(t, card) {
  return {
          cards: Belt_List.map(t.cards, (function (crd) {
                  if (crd.front === card.front && card.back === card.back) {
                    return card;
                  } else {
                    return crd;
                  }
                }))
        };
}

function updateCards(_t, _cards) {
  while(true) {
    var cards = _cards;
    var t = _t;
    if (!cards) {
      return t;
    }
    _cards = cards.tl;
    _t = updateCard(t, cards.hd);
    continue ;
  };
}

var Update = {
  addCard: addCard,
  updateCard: updateCard,
  updateCards: updateCards
};

function getByLevel(param, level) {
  return Belt_List.keep(param.cards, (function (card) {
                return card.level === level;
              }));
}

function getCards(t, iteration) {
  var reviewEach = function (day, cards) {
    if (Caml_int32.mod_(iteration, day) === 0) {
      return cards;
    } else {
      return /* [] */0;
    }
  };
  return Belt_List.concat(Belt_List.concat(Belt_List.concat(getByLevel(t, /* New */0), reviewEach(2, getByLevel(t, /* Familiar */1))), reviewEach(3, getByLevel(t, /* Remember */2))), reviewEach(4, getByLevel(t, /* Know */3)));
}

var Selectors = {
  getByLevel: getByLevel,
  getCards: getCards
};

var empty = {
  cards: /* [] */0
};

export {
  empty ,
  make ,
  Update ,
  Selectors ,
  
}
/* No side effect */
