// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Box from "./box.bs.js";
import * as Card from "./card.bs.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";

var empty_new = Box.Update.add(Box.empty, Card.make("new card fron", "the card back"));

var empty = {
  new: empty_new,
  familiar: Box.empty,
  remember: Box.empty,
  know: Box.empty,
  done: Box.empty
};

function make($$new, familiar, remember, know, done) {
  return {
          new: $$new,
          familiar: familiar,
          remember: remember,
          know: know,
          done: done
        };
}

function addCard(t, card) {
  return {
          new: Box.Update.add(t.new, card),
          familiar: t.familiar,
          remember: t.remember,
          know: t.know,
          done: t.done
        };
}

var Update = {
  addCard: addCard
};

function getBoxes(t, iteration) {
  var reviewEach = function (day, cards) {
    if (Caml_int32.mod_(iteration, day) === 0) {
      return cards;
    } else {
      return /* [] */0;
    }
  };
  return Box.make(Belt_List.concat(Belt_List.concat(Belt_List.concat(t.new.cards, reviewEach(2, t.familiar.cards)), reviewEach(3, t.remember.cards)), reviewEach(4, t.know.cards)));
}

var Selectors = {
  getBoxes: getBoxes
};

export {
  empty ,
  make ,
  Update ,
  Selectors ,
  
}
/* empty Not a pure module */
