// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "./card.bs.js";

var emptyReview = {
  toReview: /* [] */0,
  reviewing: Card.empty,
  remember: /* [] */0,
  forget: /* [] */0
};

function make(cards) {
  if (cards) {
    return /* Review */{
            _0: {
              toReview: cards.tl,
              reviewing: cards.hd,
              remember: /* [] */0,
              forget: /* [] */0
            }
          };
  } else {
    return /* Overview */0;
  }
}

function next(param, known) {
  var toReview = param.toReview;
  if (!toReview) {
    return ;
  }
  var forget = param.forget;
  var remember = param.remember;
  var reviewing = param.reviewing;
  return {
          toReview: toReview.tl,
          reviewing: toReview.hd,
          remember: known ? ({
                hd: Card.Update.next(reviewing),
                tl: remember
              }) : remember,
          forget: known ? forget : ({
                hd: Card.Update.back(reviewing),
                tl: forget
              })
        };
}

var Update = {
  next: next
};

var empty = /* Overview */0;

export {
  emptyReview ,
  empty ,
  make ,
  Update ,
  
}
/* No side effect */
