// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

var cardStyle = {
  display: "flex",
  width: "100%",
  flexDirection: "row"
};

var side = {
  border: "1px solid gray",
  flex: "1"
};

function CardComp(Props) {
  var card = Props.card;
  var selected = Props.selected;
  return React.createElement("div", {
              style: cardStyle
            }, Belt_Array.map([
                  card.front,
                  card.back
                ], (function (str) {
                    return React.createElement("div", {
                                style: side
                              }, str, selected ? " <" : "");
                  })));
}

var make = CardComp;

export {
  cardStyle ,
  side ,
  make ,
  
}
/* react Not a pure module */
