// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function CardComp(Props) {
  var card = Props.card;
  return React.createElement("div", {
              style: {
                border: "1px solid gray"
              }
            }, card.front);
}

var make = CardComp;

export {
  make ,
  
}
/* react Not a pure module */
