// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../domain/card.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "../state/state.bs.js";
import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function Form$Input(Props) {
  var value = Props.value;
  var setValue = Props.setValue;
  var onEnter = Props.onEnter;
  var onKeyDown = function (e) {
    if (e.key === "Enter") {
      return Curry._1(onEnter, undefined);
    }
    
  };
  var onChange = function (e) {
    return Curry._1(setValue, e.currentTarget.value);
  };
  return React.createElement("input", {
              value: value,
              onKeyDown: onKeyDown,
              onChange: onChange
            });
}

var Input = {
  make: Form$Input
};

function Form(Props) {
  var dispatch = Curry._1(State.AppState.useDispatch, undefined);
  var match = React.useState(function () {
        return "";
      });
  var setFront = match[1];
  var front = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setBack = match$1[1];
  var back = match$1[0];
  var onEnter = function (param) {
    var toSome = function (str) {
      if (str === "") {
        return ;
      } else {
        return str;
      }
    };
    var flatMap2 = function (ab, fn) {
      var a = ab[0];
      if (a === undefined) {
        return ;
      }
      var b = ab[1];
      if (b !== undefined) {
        return Curry._2(fn, Caml_option.valFromOption(a), Caml_option.valFromOption(b));
      }
      
    };
    Belt_Option.map(flatMap2([
              toSome(front),
              toSome(back)
            ], (function (front, back) {
                return Card.make(front, back, /* New */0);
              })), (function (card) {
            Curry._1(setFront, (function (param) {
                    return "";
                  }));
            Curry._1(setBack, (function (param) {
                    return "";
                  }));
            return Curry._1(dispatch, {
                        TAG: /* AddCard */0,
                        _0: card
                      });
          }));
    
  };
  var onClick = function (param) {
    return Curry._1(dispatch, /* StartReview */0);
  };
  return React.createElement(React.Fragment, undefined, React.createElement(Form$Input, {
                  value: front,
                  setValue: setFront,
                  onEnter: onEnter
                }), React.createElement(Form$Input, {
                  value: back,
                  setValue: setBack,
                  onEnter: onEnter
                }), React.createElement("button", {
                  onClick: onClick
                }, "Start"));
}

var make = Form;

export {
  Input ,
  make ,
  
}
/* State Not a pure module */
