// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Card from "../domain/card.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "../state/state.bs.js";
import * as React from "react";
import * as BoxComp from "./BoxComp.bs.js";
import * as TitleComp from "./TitleComp.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function Review(Props) {
  var stack = Props.stack;
  var cursor = Props.cursor;
  var dispatch = Curry._1(State.AppState.useDispatch, undefined);
  return React.createElement(React.Fragment, undefined, React.createElement(TitleComp.make, {
                  children: "Review"
                }), Belt_Array.map([
                  /* Back */0,
                  /* Skip */1,
                  /* Next */2
                ], (function (familiarity) {
                    return React.createElement("button", {
                                onClick: (function (param) {
                                    return Curry._1(dispatch, {
                                                TAG: /* Review */1,
                                                _0: familiarity
                                              });
                                  })
                              }, Card.familiarityToString(familiarity));
                  })), React.createElement(BoxComp.make, {
                  stack: stack,
                  label: "Skipped",
                  cursor: cursor
                }));
}

var make = Review;

export {
  make ,
  
}
/* State Not a pure module */
