// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Box from "../domain/box.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "../state/state.bs.js";
import * as React from "react";
import * as BoxComp from "./BoxComp.bs.js";
import * as CardComp from "./CardComp.bs.js";
import * as TitleComp from "./TitleComp.bs.js";

function Review(Props) {
  var review = Props.review;
  var dispatch = Curry._1(State.AppState.useDispatch, undefined);
  return React.createElement(React.Fragment, undefined, React.createElement(TitleComp.make, {
                  children: "Review"
                }), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Remember */1);
                    })
                }, "remember"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* Forget */2);
                    })
                }, "forget"), React.createElement(CardComp.make, {
                  card: review.reviewing
                }), React.createElement(BoxComp.make, {
                  box: Box.make(review.toReview),
                  label: "To review"
                }), React.createElement(BoxComp.make, {
                  box: Box.make(review.remember),
                  label: "Remember"
                }), React.createElement(BoxComp.make, {
                  box: Box.make(review.forget),
                  label: "Forget"
                }));
}

var make = Review;

export {
  make ,
  
}
/* State Not a pure module */
