// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TitleComp(Props) {
  var children = Props.children;
  return React.createElement("h1", undefined, children);
}

var make = TitleComp;

export {
  make ,
  
}
/* react Not a pure module */
