// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Remember from "../domain/remember.bs.js";
import * as Remporium from "remporium/src/Remporium.bs.js";

function reducer(t, action) {
  if (typeof action !== "number") {
    return Remember.Update.addCard(t, action._0);
  }
  switch (action) {
    case /* Review */0 :
        return Remember.Update.startReview(t);
    case /* Remember */1 :
        return Remember.Update.next(t, true);
    case /* Forget */2 :
        return Remember.Update.next(t, false);
    
  }
}

var store = Remporium.makeStore(Remember.empty, reducer);

var AppState = Remporium.CreateModule({});

export {
  reducer ,
  store ,
  AppState ,
  
}
/* store Not a pure module */
